server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ningg/spring-cloud-config-repo.git
          username: guoning.gn@gmail.com
          password: guoning123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/